### ISSUE TITLE
Storage queue MessageNotFound error

### ISSUE THREAD

**Issue by mike11stevens** [Azure/azure-storage-queue-go#20]
working with storage queues and am using the glang SDK at [github.com/Azure/azure-storage-queue-go/azqueue](https://github.com/Azure/azure-storage-queue-go). When updating the message visibility window it works the first time but fails on the second call with a MessageNotFound error. This works with the older Azure golang SDK at [github.com/Azure/azure-sdk-for-go/storage](https://github.com/Azure/azure-sdk-for-go)

**Comment by deepak-clumio** [comment]
Attached is a standalone golang program that uses the sdk and repros the problem. Set the env variables `AZURE_STORAGE_ACCOUNT_NAME` and `AZURE_STORAGE_ACCOUNT_KEY` and run the program.

[main.zip](https://github.com/Azure/azure-storage-queue-go/files/5228850/main.zip)

**Comment by seungjin-clumio** [comment]
The bug is caused by the fact that caller needs to manually update the receipt handle (see  https://github.com/Azure/azure-storage-queue-go/blob/636801874cdd196abace508ef19c3edca7ed0564/azqueue/zt_examples_test.go#L124). @mohsha-msft could the Update function change the receipt handle as part of the function instead of relying on the caller to update it? I don't see a case where the caller wouldn't want or expect this behavior.

**Comment by zezha-msft** [comment]
Hi,
 
The issue doesn’t seem like a bug. The SDK is representing the service API as intended, i.e. the most recent pop receipt is expected on subsequent operations. Doc:

popreceipt | Required. Specifies the valid pop receipt value returned from an earlier call to the Get Messages or Update Message operation.
-- | --

https://docs.microsoft.com/en-us/rest/api/storageservices/update-message#uri-parameters
