### ISSUE TITLE
Enqueue message timeToLive

### ISSUE THREAD

**Issue by WorldIsM** [Azure/azure-storage-queue-go#3]
Hi, 
according to https://docs.microsoft.com/en-us/rest/api/storageservices/put-message
timeToLive could be set to -1 
Lib have following code:

func (m MessagesURL) Enqueue(ctx context.Context, messageText string, visibilityTimeout time.Duration, timeToLive time.Duration) (*EnqueueMessageResponse, error) {
	vt := int32(visibilityTimeout.Seconds())
	**ttl := int32(timeToLive.Seconds())**

which replace -1 with 0. And I've got from Azure:

Reason: Value must be greater than or equal to 1, or -1 to indicate an infinite TTL.

Also lib eats real error message - I've got:
"runtime error: invalid memory address or nil pointer dereference" with no details

**Comment by pavelsmejkal** [comment]
Actually lib doesn't eats error

err is not checked and then item is accessed so code will panic in any error case. 

@zezha-msft  this is kind of serious bug. Library should not panic in any cases. 

```go

func (m MessagesURL) Enqueue(ctx context.Context, messageText string, visibilityTimeout time.Duration, timeToLive time.Duration) (*EnqueueMessageResponse, error) {
	vt := int32(visibilityTimeout.Seconds())
	ttl := int32(timeToLive.Seconds())
	er, err := m.client.Enqueue(ctx, QueueMessage{MessageText: messageText}, &vt, &ttl, nil, nil)
	item := er.Items[0]
	return &EnqueueMessageResponse{

```

**Comment by zezha-msft** [comment]
Hi @pavelsmejkal, it's indeed not ideal. I'm working on this, and will release the fix as soon as possible. Thanks!

**Comment by zezha-msft** [comment]
Hi @WorldIsM and @pavelsmejkal, I just took a closer look at this issue, and realized that there is actually no bug in this case. Here is a clarification:

The receiver Enqueue takes in a `time.Duration` for timeToLive, which represents a duration in nanoseconds. Passing in `-1` means -1 nanosecond, instead of -1 second. Thus, `-time.Second` should be passed instead; I've verified that this indeed works.

I'll make sure to improve the documentation to better the user experience.

#5 is fixed and will be released soon.
